Book.create("name"=>"Bowling for Columbine", "author"=>"Michael Moore", "read"=>true)
Book.create("name"=>"How I met your mother", "author"=>"Daddy", "read"=>true)
Book.create("name"=>"Around the world in 80 days", "author"=>"Osborne", "read"=>false)
Book.create("name"=>"Mickey's Deadly Crime", "author"=>"Walt Disney", "read"=>true)
Book.create("name"=>"The long road to happines", "author"=>"Will Smith", "read"=>false)
Book.create("name"=>"The Adventures of Ah Seng", "author"=>"Ah Lian", "read"=>true)
Book.create("name"=>"Breaking Good", "author"=>"Ralph Junior", "read"=>false)
Book.create("name"=>"Salem's Lot", "author"=>"R.L Stine", "read"=>false)
Book.create("name"=>"Ali Baba and Jack Ma", "author"=>"Mr Ma", "read"=>false)
Book.create("name"=>"Dude, Where's my car?", "author"=>"Dude", "read"=>false)
Book.create("name"=>"Ruby on Rails: Convention or Configuration?", "author"=>"Doge", "read"=>true)
Book.create("name"=>"The spy who shagged me", "author"=>"Austin Powers", "read"=>true)
Book.create("name"=>"Minority Report", "author"=>"Peter Jackson", "read"=>true)
Book.create("name"=>"The Dictator", "author"=>"Kim Jong Un", "read"=>false)
Book.create("name"=>"The Hacker's Guide to decrypting bad passwords", "author"=>"Anonymous", "read"=>true)
Book.create("name"=>"My First Six Pack", "author"=>"The Rock", "read"=>false)
Book.create("name"=>"How to score on your first date", "author"=>"Dr. Love", "read"=>false)
Book.create("name"=>"The Cat and The Mouse III", "author"=>"Sparky", "read"=>false)
Book.create("name"=>"The Chronicles of Deadpool", "author"=>"Tom Green", "read"=>true)
Book.create("name"=>"My Best Friend's Bad Habits", "author"=>"Homer", "read"=>true)
Book.create("name"=>"Star Wars: The Last Jedi", "author"=>"Yoda", "read"=>false)
Book.create("name"=>"Red sky in the morning", "author"=>"Mary J Blidge", "read"=>true)
Book.create("name"=>"The Final Sprint", "author"=>"Mr Tortoise", "read"=>true)
